// Re-export lucide-react icons with consistent defaults
// All icons use strokeWidth={1.5} for modern, clean look

export {
  Plus as PlusIcon,
  SquarePen as PencilIcon,
  Trash2 as TrashIcon,
  Check as CheckIcon,
  X as XIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  Users as UsersIcon,
  Building2 as BuildingIcon,
  Tag as TagIcon,
  Video as VideoIcon,
  KeyRound as KeyIcon,
  ArrowLeft as ArrowLeftIcon,
  Clock as ClockIcon,
  Folder as FolderIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  CircleCheckBig as CheckCircleIcon,
  ArrowUpDown as SortIcon,
  ChevronUp as SortAscIcon,
  ChevronDown as SortDescIcon,
  GripVertical as GripIcon,
  Settings as SettingsIcon,
  Home as HomeIcon,
  Menu as MenuIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  LogOut as LogOutIcon,
  Layers as LayersIcon,
  BarChart3 as BarChartIcon,
  Play as PlayIcon,
  CirclePlay as CirclePlayIcon,
  Search as SearchIcon,
  Loader2 as LoaderIcon,
  Mail as MailIcon,
  MoreVertical as MoreVerticalIcon,
  GripVertical as GripVerticalIcon,
} from "lucide-react";
